#!/usr/bin/env bash
# shellcheck disable=SC2034
# SPDX-License-Identifier: MIT
# Copyright (C) 2023 Vicharak Computers LLP

# Date for boot image
DATE=$(date +"%d.%m.%y")
export DATE

# Uboot directory path
export UBOOT_DIR="${SCRIPT_DIR}"/..

# set PS3 prompt
export PS3="Select device: "

# Host system
HOST_SYSTEM=$(grep "^ID=" /etc/os-release | cut -d'=' -f2)
export HOST_SYSTEM
